// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utneavwccpexypqhrzcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0bmVhdndjY3BleHlwcWhyemNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Nzg3MTAsImV4cCI6MjA2NjE1NDcxMH0.__dROOorAsKZBU8Fdf94-YwKjAzL9WhBBcTcklOS9pQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);